import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:shared_preferences/shared_preferences.dart';

/// Standalone, backend-free viewer for the coach's training sheet.
///
/// Loads `workouts.json` (generated by `tools/sheet_to_json.py` and published
/// next to the web build) and shows one week at a time, newest first.
/// "Done" state and the weight column preference live in the browser only.
class WeekApp extends StatelessWidget {
  const WeekApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Mi semana',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFFBF5E28),
          surface: const Color(0xFFFFF8F4),
        ),
        scaffoldBackgroundColor: const Color(0xFFFFF8F4),
        useMaterial3: true,
      ),
      home: const WeekScreen(),
    );
  }
}

class _Week {
  final String tab;
  final int month;
  final String label;
  final List<_Day> days;
  _Week({required this.tab, required this.month, required this.label, required this.days});

  String get key => '$tab|$label';
}

class _Day {
  final int number;
  final String content;
  _Day({required this.number, required this.content});
}

class WeekScreen extends StatefulWidget {
  const WeekScreen({super.key});

  @override
  State<WeekScreen> createState() => _WeekScreenState();
}

class _WeekScreenState extends State<WeekScreen> {
  static const _prefWeight = 'week.weightIndex';
  static const _prefPos = 'week.position';

  List<_Week> _weeks = [];
  int _index = 0; // position in _weeks; last = most recent
  String? _generatedAt;
  String? _error;
  bool _loading = true;

  // -1 = show both weights as written in the sheet, 0 = first, 1 = second.
  int _weightIndex = -1;
  Set<String> _done = {};
  SharedPreferences? _prefs;

  @override
  void initState() {
    super.initState();
    _load();
  }

  Future<void> _load() async {
    setState(() {
      _loading = true;
      _error = null;
    });
    try {
      _prefs ??= await SharedPreferences.getInstance();
      _weightIndex = _prefs!.getInt(_prefWeight) ?? -1;
      _done = (_prefs!.getStringList('week.done') ?? []).toSet();

      final res = await http.get(Uri.base.resolve('workouts.json'));
      if (res.statusCode != 200) {
        throw Exception('workouts.json -> HTTP ${res.statusCode}');
      }
      final data = json.decode(utf8.decode(res.bodyBytes)) as Map<String, dynamic>;
      final weeks = <_Week>[];
      for (final tab in data['tabs'] as List) {
        for (final w in tab['weeks'] as List) {
          weeks.add(_Week(
            tab: tab['title'] as String,
            month: tab['month'] as int,
            label: w['label'] as String,
            days: [
              for (final d in w['days'] as List)
                _Day(number: d['day'] as int, content: d['content'] as String),
            ],
          ));
        }
      }
      var idx = _currentWeekIndex(weeks);
      // Keep the week the user was browsing, if the sheet still has it.
      final saved = _prefs!.getString(_prefPos);
      if (saved != null) {
        final found = weeks.indexWhere((w) => w.key == saved);
        if (found >= 0) idx = found;
      }
      setState(() {
        _weeks = weeks;
        _index = idx < 0 ? 0 : idx;
        _generatedAt = data['generatedAt'] as String?;
        _loading = false;
      });
    } catch (e) {
      setState(() {
        _error = e.toString();
        _loading = false;
      });
    }
  }

  /// The current week is the last week of the last tab for this calendar
  /// month, whatever the coach named it ("Sep", "Sept", "Septi"...). If there
  /// is no tab for this month yet, fall back to the newest week in the sheet.
  static int _currentWeekIndex(List<_Week> weeks) {
    final month = DateTime.now().month;
    final idx = weeks.lastIndexWhere((w) => w.month == month);
    return idx >= 0 ? idx : weeks.length - 1;
  }

  void _go(int delta) {
    final next = _index + delta;
    if (next < 0 || next >= _weeks.length) return;
    setState(() => _index = next);
    _prefs?.setString(_prefPos, _weeks[next].key);
  }

  void _setWeight(int value) {
    setState(() => _weightIndex = value);
    _prefs?.setInt(_prefWeight, value);
  }

  String _doneKey(_Week w, _Day d) => '${w.key}|${d.number}';

  void _toggleDone(_Week w, _Day d) {
    final k = _doneKey(w, d);
    setState(() {
      if (!_done.remove(k)) _done.add(k);
    });
    _prefs?.setStringList('week.done', _done.toList());
  }

  @override
  Widget build(BuildContext context) {
    if (_loading) {
      return const Scaffold(body: Center(child: CircularProgressIndicator()));
    }
    if (_error != null || _weeks.isEmpty) {
      return Scaffold(
        body: Center(
          child: Padding(
            padding: const EdgeInsets.all(24),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                const Icon(Icons.cloud_off, size: 48),
                const SizedBox(height: 12),
                Text(_error ?? 'No hay semanas en el sheet todavía.',
                    textAlign: TextAlign.center),
                const SizedBox(height: 16),
                FilledButton(onPressed: _load, child: const Text('Reintentar')),
              ],
            ),
          ),
        ),
      );
    }

    final week = _weeks[_index];
    final isLatest = _index == _weeks.length - 1;
    final scheme = Theme.of(context).colorScheme;

    return Scaffold(
      appBar: AppBar(
        backgroundColor: scheme.surface,
        title: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(week.label, style: const TextStyle(fontWeight: FontWeight.bold)),
            Text(week.tab, style: Theme.of(context).textTheme.bodySmall),
          ],
        ),
        actions: [
          IconButton(
            tooltip: 'Semana anterior',
            onPressed: _index > 0 ? () => _go(-1) : null,
            icon: const Icon(Icons.chevron_left),
          ),
          IconButton(
            tooltip: 'Semana siguiente',
            onPressed: isLatest ? null : () => _go(1),
            icon: const Icon(Icons.chevron_right),
          ),
          IconButton(
            tooltip: 'Recargar',
            onPressed: _load,
            icon: const Icon(Icons.refresh),
          ),
        ],
      ),
      body: RefreshIndicator(
        onRefresh: _load,
        child: ListView(
          padding: const EdgeInsets.fromLTRB(16, 8, 16, 32),
          children: [
            _WeightSelector(value: _weightIndex, onChanged: _setWeight),
            const SizedBox(height: 8),
            for (final day in week.days)
              _DayCard(
                day: day,
                weightIndex: _weightIndex,
                done: _done.contains(_doneKey(week, day)),
                onToggle: () => _toggleDone(week, day),
              ),
            if (_generatedAt != null)
              Padding(
                padding: const EdgeInsets.only(top: 16),
                child: Text(
                  'Actualizado ${_formatGenerated(_generatedAt!)}',
                  textAlign: TextAlign.center,
                  style: Theme.of(context)
                      .textTheme
                      .bodySmall
                      ?.copyWith(color: scheme.outline),
                ),
              ),
          ],
        ),
      ),
    );
  }

  String _formatGenerated(String iso) {
    final d = DateTime.tryParse(iso)?.toLocal();
    if (d == null) return iso;
    String two(int n) => n.toString().padLeft(2, '0');
    return '${two(d.day)}/${two(d.month)} ${two(d.hour)}:${two(d.minute)}';
  }
}

class _WeightSelector extends StatelessWidget {
  final int value;
  final ValueChanged<int> onChanged;
  const _WeightSelector({required this.value, required this.onChanged});

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        Text('Pesos', style: Theme.of(context).textTheme.labelLarge),
        const SizedBox(width: 12),
        SegmentedButton<int>(
          showSelectedIcon: false,
          segments: const [
            ButtonSegment(value: -1, label: Text('Ambos')),
            ButtonSegment(value: 0, label: Text('1º')),
            ButtonSegment(value: 1, label: Text('2º')),
          ],
          selected: {value},
          onSelectionChanged: (s) => onChanged(s.first),
        ),
      ],
    );
  }
}

class _DayCard extends StatelessWidget {
  static final _rxc = RegExp(r'\b(\d+\s*RxC)\b', caseSensitive: false);
  static final _weights = RegExp(r'\(([\d,\.]+)/([\d,\.]+)\)');

  static const _sections = {
    '[WARMUP]': ('Estructura', Color(0xFF00796B), Color(0xFFE0F2F1)),
    '[FUERZA]': ('Fuerza', Color(0xFFE65100), Color(0xFFFFF3E0)),
    '[WOD]': ('WOD', Color(0xFFF57F17), Color(0xFFFFFDE7)),
  };

  final _Day day;
  final int weightIndex;
  final bool done;
  final VoidCallback onToggle;

  const _DayCard({
    required this.day,
    required this.weightIndex,
    required this.done,
    required this.onToggle,
  });

  String _applyWeights(String text) {
    if (weightIndex < 0) return text;
    return text.replaceAllMapped(
        _weights, (m) => '(${weightIndex == 0 ? m[1] : m[2]})');
  }

  @override
  Widget build(BuildContext context) {
    final rxc = _rxc.firstMatch(day.content)?.group(1);
    final body = _applyWeights(day.content.replaceFirst(_rxc, '').trim());

    // Split the marked text into (marker, lines) pairs, keeping sheet order.
    final blocks = <(String, List<String>)>[];
    for (final line in body.split('\n')) {
      final t = line.trim();
      if (t.isEmpty) continue;
      if (_sections.containsKey(t)) {
        blocks.add((t, []));
      } else {
        if (blocks.isEmpty) blocks.add(('[WARMUP]', []));
        blocks.last.$2.add(t);
      }
    }

    return Card(
      margin: const EdgeInsets.only(bottom: 12),
      child: Padding(
        padding: const EdgeInsets.fromLTRB(16, 8, 8, 16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Text('Día ${day.number}',
                    style: Theme.of(context)
                        .textTheme
                        .titleMedium
                        ?.copyWith(fontWeight: FontWeight.bold)),
                if (rxc != null) ...[
                  const SizedBox(width: 10),
                  Container(
                    padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
                    decoration: BoxDecoration(
                      color: const Color(0xFFBF5E28),
                      borderRadius: BorderRadius.circular(12),
                    ),
                    child: Text(rxc,
                        style: const TextStyle(
                            color: Colors.white, fontWeight: FontWeight.bold)),
                  ),
                ],
                const Spacer(),
                Checkbox(value: done, onChanged: (_) => onToggle()),
              ],
            ),
            for (final (marker, lines) in blocks)
              if (lines.isNotEmpty) _Section(marker: marker, lines: lines),
          ],
        ),
      ),
    );
  }
}

class _Section extends StatelessWidget {
  final String marker;
  final List<String> lines;
  const _Section({required this.marker, required this.lines});

  @override
  Widget build(BuildContext context) {
    final (title, fg, bg) = _DayCard._sections[marker]!;
    return Container(
      width: double.infinity,
      margin: const EdgeInsets.only(top: 8, right: 8),
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: bg,
        borderRadius: BorderRadius.circular(8),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(title,
              style: TextStyle(
                  color: fg, fontWeight: FontWeight.bold, letterSpacing: 0.5)),
          const SizedBox(height: 4),
          for (final l in lines) Text(l, style: const TextStyle(height: 1.4)),
        ],
      ),
    );
  }
}
