import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:shared_preferences/shared_preferences.dart';

/// Viewer for the coach's training sheet.
///
/// Loads `workouts.json` (generated by `tools/sheet_to_json.py` and published
/// next to the web build) and shows one week at a time, newest first.
/// "Done" state and the weight column preference live in the browser only.
///
/// When built with `--dart-define=APPS_SCRIPT_URL=...` it also talks to
/// `apps_script/Code.gs` (bound to the sheet) for weight notes per person and
/// coach edits of a day. Without it, those features are simply hidden.
const _apiUrl = String.fromEnvironment('APPS_SCRIPT_URL');

const _people = ['Ale', 'Fabita'];

class WeekApp extends StatelessWidget {
  const WeekApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Mi semana',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFFBF5E28),
          surface: const Color(0xFFFFF8F4),
        ),
        scaffoldBackgroundColor: const Color(0xFFFFF8F4),
        useMaterial3: true,
      ),
      home: const WeekScreen(),
    );
  }
}

class _Week {
  final String tab;
  final String title; // the sheet tab's own title, used to address it
  final int month;
  final String label;
  final DateTime start;
  final DateTime end;
  final List<_Day> days;
  _Week({
    required this.tab,
    required this.title,
    required this.month,
    required this.label,
    required this.start,
    required this.end,
    required this.days,
  });

  String get key => '$tab|$label';

  bool contains(DateTime d) =>
      !d.isBefore(start) && d.isBefore(end.add(const Duration(days: 1)));

  /// "21 – 27 sep" or "28 sep – 4 oct" when the week straddles two months.
  String get dateRange {
    const m = ['ene', 'feb', 'mar', 'abr', 'may', 'jun', 'jul', 'ago', 'sep', 'oct', 'nov', 'dic'];
    if (start.month == end.month) {
      return '${start.day} – ${end.day} ${m[end.month - 1]}';
    }
    return '${start.day} ${m[start.month - 1]} – ${end.day} ${m[end.month - 1]}';
  }
}

class _Day {
  final int number;
  String content;
  _Day({required this.number, required this.content});
}

/// Splits marked day content into (marker, lines) blocks, keeping sheet order.
List<(String, List<String>)> _splitSections(String content) {
  final blocks = <(String, List<String>)>[];
  for (final line in content.split('\n')) {
    final t = line.trim();
    if (t.isEmpty) continue;
    if (_DayCard._sections.containsKey(t)) {
      blocks.add((t, []));
    } else {
      if (blocks.isEmpty) blocks.add(('[WARMUP]', []));
      blocks.last.$2.add(t);
    }
  }
  return blocks;
}

/// Inverse of [_splitSections] for the three editable parts of a day.
String _joinSections(String estructura, String fuerza, String wod) {
  final out = <String>[];
  for (final (marker, text) in [
    ('[WARMUP]', estructura),
    ('[FUERZA]', fuerza),
    ('[WOD]', wod),
  ]) {
    final lines = text.split('\n').map((l) => l.trim()).where((l) => l.isNotEmpty);
    if (lines.isEmpty) continue;
    out
      ..add(marker)
      ..addAll(lines);
  }
  return out.join('\n');
}

/// Minimal client for apps_script/Code.gs. Throws with the script's message.
class _Api {
  static Future<Map<String, dynamic>> get() async {
    final res = await http.get(Uri.parse('$_apiUrl?action=data'));
    return _decode(res);
  }

  // text/plain keeps it a "simple" request, so the browser skips the CORS
  // preflight that Apps Script can't answer.
  static Future<Map<String, dynamic>> post(Map<String, dynamic> body) async {
    final res = await http.post(
      Uri.parse(_apiUrl),
      headers: {'Content-Type': 'text/plain;charset=utf-8'},
      body: json.encode(body),
    );
    return _decode(res);
  }

  static Map<String, dynamic> _decode(http.Response res) {
    if (res.statusCode != 200) throw Exception('HTTP ${res.statusCode}');
    final data = json.decode(utf8.decode(res.bodyBytes)) as Map<String, dynamic>;
    if (data['error'] != null) throw Exception(data['error']);
    return data;
  }
}

class WeekScreen extends StatefulWidget {
  const WeekScreen({super.key});

  @override
  State<WeekScreen> createState() => _WeekScreenState();
}

class _WeekScreenState extends State<WeekScreen> {
  static const _prefWeight = 'week.weightIndex';

  List<_Week> _weeks = [];
  int _index = 0; // position in _weeks; last = most recent
  String? _generatedAt;
  String? _error;
  bool _loading = true;

  // -1 = show both weights as written in the sheet,
  // 0 = Ale (the heavier of the pair), 1 = Fabita (the lighter).
  int _weightIndex = -1;
  Set<String> _done = {};
  SharedPreferences? _prefs;

  static const _prefCoachPin = 'week.coachPin';
  String? _coachPin; // set once the coach entered a valid PIN on this browser
  // "tab|week|day" -> person -> note text, from the sheet's "Notas" tab.
  Map<String, Map<String, String>> _notes = {};
  String? _apiError;
  bool _remoteLoading = false;

  bool get _isCoach => _coachPin != null;

  @override
  void initState() {
    super.initState();
    _load();
  }

  Future<void> _load() async {
    setState(() {
      _loading = true;
      _error = null;
    });
    try {
      _prefs ??= await SharedPreferences.getInstance();
      final firstVisit = !_prefs!.containsKey(_prefWeight);
      _weightIndex = _prefs!.getInt(_prefWeight) ?? -1;
      _done = (_prefs!.getStringList('week.done') ?? []).toSet();
      _coachPin = _prefs!.getString(_prefCoachPin);

      // GitHub Pages caches for 10 minutes; a unique query string bypasses it.
      final res = await http.get(Uri.base.resolve(
          'workouts.json?t=${DateTime.now().millisecondsSinceEpoch}'));
      if (res.statusCode != 200) {
        throw Exception('workouts.json -> HTTP ${res.statusCode}');
      }
      final data = json.decode(utf8.decode(res.bodyBytes)) as Map<String, dynamic>;
      final weeks = <_Week>[];
      for (final tab in data['tabs'] as List) {
        for (final w in tab['weeks'] as List) {
          weeks.add(_Week(
            tab: (tab['name'] ?? tab['title']) as String,
            title: tab['title'] as String,
            month: tab['month'] as int,
            label: w['label'] as String,
            start: DateTime.parse(w['start'] as String),
            end: DateTime.parse(w['end'] as String),
            days: [
              for (final d in w['days'] as List)
                _Day(number: d['day'] as int, content: d['content'] as String),
            ],
          ));
        }
      }
      final generatedAt = data['generatedAt'] as String?;
      setState(() {
        _weeks = weeks;
        _index = weeks.isEmpty ? 0 : _currentWeekIndex(weeks);
        _generatedAt = generatedAt;
        _loading = false;
      });
      // Not awaited: the Apps Script takes seconds to answer, so the week
      // shows first and notes/edits fill in when they arrive.
      _loadRemote(weeks, generatedAt);
      if (firstVisit && mounted) _askWhoIsThis();
    } catch (e) {
      setState(() {
        _error = e.toString();
        _loading = false;
      });
    }
  }

  static String _noteKey(String tab, String week, int day) => '$tab|$week|$day';

  /// Reads notes and coach edits from the Apps Script. Edits newer than
  /// workouts.json replace that day's content, so they show up right away
  /// instead of after the next daily build. A failure here never blocks the
  /// training itself: the error is shown and the JSON content is kept.
  Future<void> _loadRemote(List<_Week> weeks, String? generatedAt) async {
    if (_apiUrl.isEmpty) return;
    setState(() {
      _apiError = null;
      _remoteLoading = true;
    });
    try {
      final data = await _Api.get();
      final notes = <String, Map<String, String>>{};
      for (final n in data['notes'] as List) {
        final k = _noteKey(n['tab'] as String, n['week'] as String, n['day'] as int);
        (notes[k] ??= {})[n['person'] as String] = n['text'] as String;
      }
      final built = DateTime.tryParse(generatedAt ?? '');
      final byKey = {
        for (final w in weeks)
          for (final d in w.days) _noteKey(w.title, w.label, d.number): d,
      };
      // Rows come oldest first, so the last edit of a day wins.
      for (final e in data['edits'] as List) {
        final updated = DateTime.tryParse(e['updated'] as String? ?? '');
        if (built != null && updated != null && !updated.isAfter(built)) continue;
        final day = byKey[_noteKey(e['tab'] as String, e['week'] as String, e['day'] as int)];
        day?.content = _joinSections(
            e['estructura'] as String, e['fuerza'] as String, e['wod'] as String);
      }
      if (!mounted) return;
      setState(() {
        _notes = notes;
        _remoteLoading = false;
      });
    } catch (e) {
      if (!mounted) return;
      setState(() {
        _apiError = 'No se pudieron cargar las notas: $e';
        _remoteLoading = false;
      });
    }
  }

  bool _canEditNote(String person) =>
      _isCoach || (_weightIndex >= 0 && _people[_weightIndex] == person);

  Future<void> _editNote(_Week w, _Day d, String person) async {
    final k = _noteKey(w.title, w.label, d.number);
    final text = await _textDialog(
      title: 'Pesos de $person · Día ${d.number}',
      initial: _notes[k]?[person] ?? '',
      hint: 'Ej: high hang snatch hasta 45 kg',
    );
    if (text == null) return;
    await _send({
      'action': 'note',
      'tab': w.title,
      'week': w.label,
      'day': d.number,
      'person': person,
      'text': text,
    }, onOk: () {
      if (text.trim().isEmpty) {
        _notes[k]?.remove(person);
      } else {
        (_notes[k] ??= {})[person] = text.trim();
      }
    });
  }

  Future<void> _editDay(_Week w, _Day d) async {
    String part(String marker) => _splitSections(d.content)
        .where((b) => b.$1 == marker)
        .expand((b) => b.$2)
        .join('\n');
    final result = await showDialog<(String, String, String)>(
      context: context,
      builder: (ctx) => _EditDayDialog(
        title: '${w.label} · Día ${d.number}',
        estructura: part('[WARMUP]'),
        fuerza: part('[FUERZA]'),
        wod: part('[WOD]'),
      ),
    );
    if (result == null) return;
    final (estructura, fuerza, wod) = result;
    await _send({
      'action': 'editDay',
      'pin': _coachPin,
      'tab': w.title,
      'week': w.label,
      'day': d.number,
      'estructura': estructura,
      'fuerza': fuerza,
      'wod': wod,
    }, onOk: () => d.content = _joinSections(estructura, fuerza, wod));
  }

  /// Posts to the Apps Script and applies [onOk] only once the sheet accepted it.
  Future<void> _send(Map<String, dynamic> body, {required VoidCallback onOk}) async {
    final messenger = ScaffoldMessenger.of(context);
    // The Apps Script often takes several seconds; say so right away.
    messenger.showSnackBar(const SnackBar(
        content: Text('Guardando…'), duration: Duration(seconds: 30)));
    try {
      await _Api.post(body);
      setState(onOk);
      messenger
        ..hideCurrentSnackBar()
        ..showSnackBar(const SnackBar(content: Text('Guardado')));
    } catch (e) {
      messenger
        ..hideCurrentSnackBar()
        ..showSnackBar(SnackBar(content: Text('No se guardó: $e')));
    }
  }

  Future<String?> _textDialog({
    required String title,
    required String initial,
    String? hint,
    bool obscure = false,
    String action = 'Guardar',
  }) {
    final controller = TextEditingController(text: initial);
    return showDialog<String>(
      context: context,
      builder: (ctx) => AlertDialog(
        title: Text(title),
        content: TextField(
          controller: controller,
          autofocus: true,
          obscureText: obscure,
          minLines: obscure ? 1 : 2,
          maxLines: obscure ? 1 : 6,
          decoration: InputDecoration(hintText: hint),
        ),
        actions: [
          TextButton(onPressed: () => Navigator.pop(ctx), child: const Text('Cancelar')),
          FilledButton(
            onPressed: () => Navigator.pop(ctx, controller.text),
            child: Text(action),
          ),
        ],
      ),
    );
  }

  /// Asks for the coach PIN and checks it against the script before
  /// remembering it on this browser. Returns whether it was accepted.
  Future<bool> _enterCoach() async {
    final pin = await _textDialog(
        title: 'PIN de entrenador', initial: '', obscure: true, action: 'Entrar');
    if (pin == null || pin.isEmpty || !mounted) return false;
    final messenger = ScaffoldMessenger.of(context);
    try {
      final res = await _Api.post({'action': 'checkPin', 'pin': pin});
      if (res['ok'] != true) {
        messenger.showSnackBar(const SnackBar(content: Text('PIN incorrecto')));
        return false;
      }
    } catch (e) {
      messenger.showSnackBar(SnackBar(content: Text('No se pudo comprobar el PIN: $e')));
      return false;
    }
    setState(() => _coachPin = pin);
    _prefs?.setString(_prefCoachPin, pin);
    return true;
  }

  void _leaveCoach() {
    setState(() => _coachPin = null);
    _prefs?.remove(_prefCoachPin);
  }

  /// The week whose dates contain today. If the coach hasn't written it yet,
  /// the last week of this calendar month's tab; failing that, the newest week.
  static int _currentWeekIndex(List<_Week> weeks) {
    final now = DateTime.now();
    final today = DateTime(now.year, now.month, now.day);
    var idx = weeks.lastIndexWhere((w) => w.contains(today));
    if (idx < 0) idx = weeks.lastIndexWhere((w) => w.month == today.month);
    return idx >= 0 ? idx : weeks.length - 1;
  }

  void _go(int delta) {
    final next = _index + delta;
    if (next < 0 || next >= _weeks.length) return;
    setState(() => _index = next);
  }

  /// First visit on this browser: ask who is reading so the right weight
  /// column is shown from now on. The chips let anyone change it later.
  Future<void> _askWhoIsThis() async {
    final picked = await showDialog<int>(
      context: context,
      barrierDismissible: false,
      builder: (ctx) => AlertDialog(
        title: const Text('¿Quién eres?'),
        content: const Text('Para mostrarte tus pesos. Lo puedes cambiar luego arriba.'),
        actions: [
          FilledButton(
            onPressed: () => Navigator.pop(ctx, 0),
            child: const Text('Ale'),
          ),
          FilledButton(
            onPressed: () => Navigator.pop(ctx, 1),
            child: const Text('Fabita Rumana Portillo'),
          ),
          if (_apiUrl.isNotEmpty)
            OutlinedButton(
              onPressed: () => Navigator.pop(ctx, 2),
              child: const Text('Entrenador'),
            ),
        ],
      ),
    );
    if (picked == null) return;
    if (picked == 2) {
      // The coach sees both weights; a wrong PIN just leaves "Ambos".
      _setWeight(-1);
      await _enterCoach();
    } else {
      _setWeight(picked);
    }
  }

  void _setWeight(int value) {
    setState(() => _weightIndex = value);
    _prefs?.setInt(_prefWeight, value);
  }

  String _doneKey(_Week w, _Day d) => '${w.key}|${d.number}';

  void _toggleDone(_Week w, _Day d) {
    final k = _doneKey(w, d);
    setState(() {
      if (!_done.remove(k)) _done.add(k);
    });
    _prefs?.setStringList('week.done', _done.toList());
  }

  @override
  Widget build(BuildContext context) {
    if (_loading) {
      return const Scaffold(body: Center(child: CircularProgressIndicator()));
    }
    if (_error != null || _weeks.isEmpty) {
      return Scaffold(
        body: Center(
          child: Padding(
            padding: const EdgeInsets.all(24),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                const Icon(Icons.cloud_off, size: 48),
                const SizedBox(height: 12),
                Text(_error ?? 'No hay semanas en el sheet todavía.',
                    textAlign: TextAlign.center),
                const SizedBox(height: 16),
                FilledButton(onPressed: _load, child: const Text('Reintentar')),
              ],
            ),
          ),
        ),
      );
    }

    final week = _weeks[_index];
    final isLatest = _index == _weeks.length - 1;
    final scheme = Theme.of(context).colorScheme;

    return Scaffold(
      appBar: AppBar(
        backgroundColor: scheme.surface,
        title: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text('${week.label} · ${week.dateRange}',
                style: const TextStyle(fontWeight: FontWeight.bold)),
            Text(week.tab, style: Theme.of(context).textTheme.bodySmall),
          ],
        ),
        actions: [
          IconButton(
            tooltip: 'Semana anterior',
            onPressed: _index > 0 ? () => _go(-1) : null,
            icon: const Icon(Icons.chevron_left),
          ),
          IconButton(
            tooltip: 'Semana siguiente',
            onPressed: isLatest ? null : () => _go(1),
            icon: const Icon(Icons.chevron_right),
          ),
          IconButton(
            tooltip: 'Recargar',
            onPressed: _load,
            icon: const Icon(Icons.refresh),
          ),
        ],
      ),
      body: RefreshIndicator(
        onRefresh: _load,
        child: ListView(
          padding: const EdgeInsets.fromLTRB(16, 8, 16, 32),
          children: [
            _WeightSelector(value: _weightIndex, onChanged: _setWeight),
            if (_apiUrl.isNotEmpty)
              Align(
                alignment: Alignment.centerLeft,
                child: _isCoach
                    ? TextButton.icon(
                        onPressed: _leaveCoach,
                        icon: const Icon(Icons.logout, size: 18),
                        label: const Text('Modo entrenador · salir'),
                      )
                    : TextButton.icon(
                        onPressed: _enterCoach,
                        icon: const Icon(Icons.lock_outline, size: 18),
                        label: const Text('Soy el entrenador'),
                      ),
              ),
            if (_remoteLoading)
              Padding(
                padding: const EdgeInsets.only(bottom: 8),
                child: Text('Cargando notas…',
                    style: TextStyle(color: scheme.outline)),
              ),
            if (_apiError != null)
              Padding(
                padding: const EdgeInsets.only(bottom: 8),
                child: Text(_apiError!, style: TextStyle(color: scheme.error)),
              ),
            const SizedBox(height: 8),
            for (final day in week.days)
              _DayCard(
                day: day,
                weightIndex: _weightIndex,
                done: _done.contains(_doneKey(week, day)),
                onToggle: () => _toggleDone(week, day),
                notes: _apiUrl.isEmpty
                    ? null
                    : _notes[_noteKey(week.title, week.label, day.number)] ?? const {},
                canEditNote: _canEditNote,
                onEditNote: (person) => _editNote(week, day, person),
                onEdit: _isCoach ? () => _editDay(week, day) : null,
              ),
            if (_generatedAt != null)
              Padding(
                padding: const EdgeInsets.only(top: 16),
                child: Text(
                  'Actualizado ${_formatGenerated(_generatedAt!)}',
                  textAlign: TextAlign.center,
                  style: Theme.of(context)
                      .textTheme
                      .bodySmall
                      ?.copyWith(color: scheme.outline),
                ),
              ),
          ],
        ),
      ),
    );
  }

  String _formatGenerated(String iso) {
    final d = DateTime.tryParse(iso)?.toLocal();
    if (d == null) return iso;
    String two(int n) => n.toString().padLeft(2, '0');
    return '${two(d.day)}/${two(d.month)} ${two(d.hour)}:${two(d.minute)}';
  }
}

class _WeightSelector extends StatelessWidget {
  final int value;
  final ValueChanged<int> onChanged;
  const _WeightSelector({required this.value, required this.onChanged});

  @override
  Widget build(BuildContext context) {
    const options = [(-1, 'Ambos'), (0, 'Ale'), (1, 'Fabita Rumana Portillo')];
    return Wrap(
      spacing: 8,
      runSpacing: 4,
      crossAxisAlignment: WrapCrossAlignment.center,
      children: [
        Text('Pesos', style: Theme.of(context).textTheme.labelLarge),
        for (final (v, label) in options)
          ChoiceChip(
            label: Text(label),
            selected: value == v,
            onSelected: (_) => onChanged(v),
          ),
      ],
    );
  }
}

class _DayCard extends StatelessWidget {
  static final _rxc = RegExp(r'\b(\d+\s*RxC)\b', caseSensitive: false);
  static final _weights = RegExp(r'\(([\d,\.]+)/([\d,\.]+)\)');

  static const _sections = {
    '[WARMUP]': ('Estructura', Color(0xFF00796B), Color(0xFFE0F2F1)),
    '[FUERZA]': ('Fuerza', Color(0xFFE65100), Color(0xFFFFF3E0)),
    '[WOD]': ('WOD', Color(0xFFF57F17), Color(0xFFFFFDE7)),
  };

  final _Day day;
  final int weightIndex;
  final bool done;
  final VoidCallback onToggle;
  final Map<String, String>? notes; // null when notes are not configured
  final bool Function(String person) canEditNote;
  final ValueChanged<String> onEditNote;
  final VoidCallback? onEdit; // coach only

  const _DayCard({
    required this.day,
    required this.weightIndex,
    required this.done,
    required this.onToggle,
    required this.notes,
    required this.canEditNote,
    required this.onEditNote,
    required this.onEdit,
  });

  /// Keeps the heavier weight of each "(X/Y)" pair for Ale and the lighter
  /// one for Fabita, regardless of the order the coach wrote them in.
  String _applyWeights(String text) {
    if (weightIndex < 0) return text;
    return text.replaceAllMapped(_weights, (m) {
      final a = m[1]!, b = m[2]!;
      final na = double.tryParse(a.replaceAll(',', '.')) ?? 0;
      final nb = double.tryParse(b.replaceAll(',', '.')) ?? 0;
      final heavier = na >= nb ? a : b;
      final lighter = na >= nb ? b : a;
      return '(${weightIndex == 0 ? heavier : lighter})';
    });
  }

  @override
  Widget build(BuildContext context) {
    final rxc = _rxc.firstMatch(day.content)?.group(1);
    final body = _applyWeights(day.content.replaceFirst(_rxc, '').trim());

    final blocks = _splitSections(body);

    return Card(
      margin: const EdgeInsets.only(bottom: 12),
      child: Padding(
        padding: const EdgeInsets.fromLTRB(16, 8, 8, 16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Text('Día ${day.number}',
                    style: Theme.of(context)
                        .textTheme
                        .titleMedium
                        ?.copyWith(fontWeight: FontWeight.bold)),
                if (rxc != null) ...[
                  const SizedBox(width: 10),
                  Container(
                    padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
                    decoration: BoxDecoration(
                      color: const Color(0xFFBF5E28),
                      borderRadius: BorderRadius.circular(12),
                    ),
                    child: Text(rxc,
                        style: const TextStyle(
                            color: Colors.white, fontWeight: FontWeight.bold)),
                  ),
                ],
                const Spacer(),
                if (onEdit != null)
                  IconButton(
                    tooltip: 'Editar día',
                    onPressed: onEdit,
                    icon: const Icon(Icons.edit_outlined),
                  ),
                Checkbox(value: done, onChanged: (_) => onToggle()),
              ],
            ),
            for (final (marker, lines) in blocks)
              if (lines.isNotEmpty) _Section(marker: marker, lines: lines),
            if (notes != null) _notesBox(context, notes!),
          ],
        ),
      ),
    );
  }
}

extension on _DayCard {
  /// "Pesos logrados": one line per person; the pencil only shows on the
  /// lines this viewer may edit (their own, or both for the coach).
  Widget _notesBox(BuildContext context, Map<String, String> notes) {
    final muted = Theme.of(context).colorScheme.outline;
    return Container(
      width: double.infinity,
      margin: const EdgeInsets.only(top: 8, right: 8),
      padding: const EdgeInsets.fromLTRB(12, 8, 4, 8),
      decoration: BoxDecoration(
        border: Border.all(color: const Color(0xFFBF5E28).withValues(alpha: 0.4)),
        borderRadius: BorderRadius.circular(8),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text('Pesos logrados',
              style: TextStyle(
                  color: Color(0xFFBF5E28),
                  fontWeight: FontWeight.bold,
                  letterSpacing: 0.5)),
          for (final person in _people)
            Row(
              crossAxisAlignment: CrossAxisAlignment.center,
              children: [
                Expanded(
                  child: Text.rich(TextSpan(children: [
                    TextSpan(
                        text: '$person: ',
                        style: const TextStyle(fontWeight: FontWeight.w600)),
                    TextSpan(
                      text: notes[person] ?? '—',
                      style: TextStyle(
                          height: 1.4, color: notes[person] == null ? muted : null),
                    ),
                  ])),
                ),
                if (canEditNote(person))
                  IconButton(
                    tooltip: 'Anotar pesos de $person',
                    visualDensity: VisualDensity.compact,
                    onPressed: () => onEditNote(person),
                    icon: const Icon(Icons.edit_note),
                  )
                else
                  const SizedBox(height: 40),
              ],
            ),
        ],
      ),
    );
  }
}

/// Coach-only editor for one day, split like the card: Estructura / Fuerza / WOD.
class _EditDayDialog extends StatefulWidget {
  final String title;
  final String estructura;
  final String fuerza;
  final String wod;
  const _EditDayDialog({
    required this.title,
    required this.estructura,
    required this.fuerza,
    required this.wod,
  });

  @override
  State<_EditDayDialog> createState() => _EditDayDialogState();
}

class _EditDayDialogState extends State<_EditDayDialog> {
  late final _estructura = TextEditingController(text: widget.estructura);
  late final _fuerza = TextEditingController(text: widget.fuerza);
  late final _wod = TextEditingController(text: widget.wod);

  @override
  void dispose() {
    _estructura.dispose();
    _fuerza.dispose();
    _wod.dispose();
    super.dispose();
  }

  Widget _field(String label, TextEditingController c) => Padding(
        padding: const EdgeInsets.only(bottom: 12),
        child: TextField(
          controller: c,
          minLines: 3,
          maxLines: 12,
          decoration: InputDecoration(labelText: label, border: const OutlineInputBorder()),
        ),
      );

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: Text(widget.title),
      content: SizedBox(
        width: 480,
        child: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              _field('Estructura (incluye "N RxC")', _estructura),
              _field('Fuerza', _fuerza),
              _field('WOD', _wod),
              Text('Se guarda en el Sheet, en la pestaña del mes.',
                  style: Theme.of(context).textTheme.bodySmall),
            ],
          ),
        ),
      ),
      actions: [
        TextButton(onPressed: () => Navigator.pop(context), child: const Text('Cancelar')),
        FilledButton(
          onPressed: () =>
              Navigator.pop(context, (_estructura.text, _fuerza.text, _wod.text)),
          child: const Text('Guardar'),
        ),
      ],
    );
  }
}

class _Section extends StatelessWidget {
  final String marker;
  final List<String> lines;
  const _Section({required this.marker, required this.lines});

  @override
  Widget build(BuildContext context) {
    final (title, fg, bg) = _DayCard._sections[marker]!;
    return Container(
      width: double.infinity,
      margin: const EdgeInsets.only(top: 8, right: 8),
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: bg,
        borderRadius: BorderRadius.circular(8),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(title,
              style: TextStyle(
                  color: fg, fontWeight: FontWeight.bold, letterSpacing: 0.5)),
          const SizedBox(height: 4),
          for (final l in lines) Text(l, style: const TextStyle(height: 1.4)),
        ],
      ),
    );
  }
}
