I dont have spring.application.name=crossfit-app

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/crossfit_db
spring.datasource.username=crossfit_user
spring.datasource.password=crossfit123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
