spring.application.name=crossfit-app

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/crossfit_db
spring.datasource.username=crossfit_user
spring.datasource.password=crossfit123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# JWT
jwt.secret=crossfit-super-secret-key-must-be-at-least-256-bits-long-for-hs256
jwt.expiration-ms=86400000

# ExerciseDB (RapidAPI)
exercisedb.api.key=7e3754e4e3msh788c1ffaafd35e5p1a6383jsnb270927d2aa9

